spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db/sampledb
    username: username
    password: password

  h2:
    console:
      enabled: true
      path: /h2-console

#起動時にAWSスタックを自動検出する設定を無効化
cloud:
  aws:
    stack:
      auto: false
    credentials:
      instance-profile: false